databaseHome: build/db-prod

database:
  driverClass: org.apache.derby.jdbc.EmbeddedDriver
  user: walking_skeleton
  url: jdbc:derby:walking-skeleton;create=true

  validationQuery: values 1
  maxWaitForConnection: 1s
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
